version: '3.3'
services:
    cameraevents:
        network_mode: web
        container_name: camera-events-pwa
        image: camera-events-pwa:latest
        environment:
            - BACKEND_URL=$BACKEND_URL